import { Contact, Company, Deal, Activity } from './types';

export const MOCK_COMPANIES: Company[] = [
  {
    id: 'comp-1',
    name: 'Vercelify Dynamics',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    domain: 'vercelify.io',
    industry: 'Cloud Infrastructure',
    size: '250-500',
    tier: 'Enterprise',
    arr: 148000,
    openDeals: 2,
    location: 'San Francisco, CA',
    owner: 'Elena Rostova',
  },
  {
    id: 'comp-2',
    name: 'Stripeflow AI',
    logo: 'https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=100&auto=format&fit=crop&q=80',
    domain: 'stripeflow.ai',
    industry: 'Fintech & Payments',
    size: '100-250',
    tier: 'Mid-Market',
    arr: 96000,
    openDeals: 2,
    location: 'New York, NY',
    owner: 'Marcus Chen',
  },
  {
    id: 'comp-3',
    name: 'Kinetics Robotics',
    logo: 'https://images.unsplash.com/photo-1550751827-4bd374c3f58b?w=100&auto=format&fit=crop&q=80',
    domain: 'kinetics.tech',
    industry: 'Autonomous Hardware',
    size: '50-100',
    tier: 'Growth',
    arr: 72000,
    openDeals: 1,
    location: 'Boston, MA',
    owner: 'Sarah Jenkins',
  },
  {
    id: 'comp-4',
    name: 'Loomis Security',
    logo: 'https://images.unsplash.com/photo-1563986768609-322da13575f3?w=100&auto=format&fit=crop&q=80',
    domain: 'loomissecur.com',
    industry: 'Cybersecurity',
    size: '500-1000',
    tier: 'Enterprise',
    arr: 220000,
    openDeals: 2,
    location: 'Austin, TX',
    owner: 'Marcus Chen',
  },
  {
    id: 'comp-5',
    name: 'Chronos Logistics',
    logo: 'https://images.unsplash.com/photo-1579546929518-9e396f3cc809?w=100&auto=format&fit=crop&q=80',
    domain: 'chronoslog.com',
    industry: 'Supply Chain Ops',
    size: '1000+',
    tier: 'Enterprise',
    arr: 310000,
    openDeals: 1,
    location: 'Chicago, IL',
    owner: 'Elena Rostova',
  },
  {
    id: 'comp-6',
    name: 'HyperScale Health',
    logo: 'https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?w=100&auto=format&fit=crop&q=80',
    domain: 'hyperscalehealth.org',
    industry: 'Health Tech',
    size: '50-100',
    tier: 'Growth',
    arr: 54000,
    openDeals: 1,
    location: 'Seattle, WA',
    owner: 'Alex Rivera',
  },
  {
    id: 'comp-7',
    name: 'Synthetix Media',
    logo: 'https://images.unsplash.com/photo-1507238691740-187a5b1d37b8?w=100&auto=format&fit=crop&q=80',
    domain: 'synthetix.design',
    industry: 'Creative & Media',
    size: '20-50',
    tier: 'Startup',
    arr: 32000,
    openDeals: 1,
    location: 'Los Angeles, CA',
    owner: 'Sarah Jenkins',
  },
  {
    id: 'comp-8',
    name: 'Novus Retail Group',
    logo: 'https://images.unsplash.com/photo-1542744094-3a31f272c490?w=100&auto=format&fit=crop&q=80',
    domain: 'novusretail.com',
    industry: 'E-Commerce',
    size: '250-500',
    tier: 'Mid-Market',
    arr: 88000,
    openDeals: 2,
    location: 'Denver, CO',
    owner: 'Alex Rivera',
  },
];

export const MOCK_CONTACTS: Contact[] = [
  {
    id: 'c-1',
    name: 'Alana Vance',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80',
    email: 'alana@vercelify.io',
    phone: '+1 (415) 890-2101',
    title: 'VP of Infrastructure',
    company: 'Vercelify Dynamics',
    companyId: 'comp-1',
    status: 'Customer',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80', email: 'elena@orbitcrm.com' },
    lastContacted: '2 hours ago',
    value: 84000,
    location: 'San Francisco, CA',
    notesCount: 5,
    tags: ['Champion', 'Key Decision Maker', 'Tier 1'],
  },
  {
    id: 'c-2',
    name: 'Devon Mercer',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80',
    email: 'devon@stripeflow.ai',
    phone: '+1 (212) 433-8991',
    title: 'Chief Technology Officer',
    company: 'Stripeflow AI',
    companyId: 'comp-2',
    status: 'Active',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80', email: 'marcus@orbitcrm.com' },
    lastContacted: 'Yesterday',
    value: 62000,
    location: 'New York, NY',
    notesCount: 8,
    tags: ['Technical Buyer', 'Fintech'],
  },
  {
    id: 'c-3',
    name: 'Hanna Lindqvist',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    email: 'hanna@kinetics.tech',
    phone: '+1 (617) 502-3341',
    title: 'Head of Operations',
    company: 'Kinetics Robotics',
    companyId: 'comp-3',
    status: 'Active',
    owner: { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80', email: 'sarah@orbitcrm.com' },
    lastContacted: '3 days ago',
    value: 48000,
    location: 'Boston, MA',
    notesCount: 3,
    tags: ['Operations', 'Hardware'],
  },
  {
    id: 'c-4',
    name: 'Julian Sterling',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80',
    email: 'jsterling@loomissecur.com',
    phone: '+1 (512) 349-1120',
    title: 'Chief Information Security Officer',
    company: 'Loomis Security',
    companyId: 'comp-4',
    status: 'Customer',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80', email: 'marcus@orbitcrm.com' },
    lastContacted: 'Oct 12',
    value: 120000,
    location: 'Austin, TX',
    notesCount: 11,
    tags: ['Security Exec', 'Renewal Q4'],
  },
  {
    id: 'c-5',
    name: 'Claire Dupont',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?w=120&auto=format&fit=crop&q=80',
    email: 'cdupont@chronoslog.com',
    phone: '+1 (312) 774-0982',
    title: 'Global Supply Director',
    company: 'Chronos Logistics',
    companyId: 'comp-5',
    status: 'Lead',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80', email: 'elena@orbitcrm.com' },
    lastContacted: '4 hours ago',
    value: 175000,
    location: 'Chicago, IL',
    notesCount: 2,
    tags: ['Inbound', 'High Intent'],
  },
  {
    id: 'c-6',
    name: 'Mateo Morales',
    avatar: 'https://images.unsplash.com/photo-1492562080023-ab3db95bfbce?w=120&auto=format&fit=crop&q=80',
    email: 'mateo@hyperscalehealth.org',
    phone: '+1 (206) 881-2299',
    title: 'VP Clinical Systems',
    company: 'HyperScale Health',
    companyId: 'comp-6',
    status: 'Active',
    owner: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80', email: 'alex@orbitcrm.com' },
    lastContacted: '5 days ago',
    value: 54000,
    location: 'Seattle, WA',
    notesCount: 4,
    tags: ['HIPAA', 'Compliance'],
  },
  {
    id: 'c-7',
    name: 'Zoe Nakamura',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=120&auto=format&fit=crop&q=80',
    email: 'zoe@synthetix.design',
    phone: '+1 (310) 902-8811',
    title: 'Creative Systems Lead',
    company: 'Synthetix Media',
    companyId: 'comp-7',
    status: 'Lead',
    owner: { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80', email: 'sarah@orbitcrm.com' },
    lastContacted: '1 week ago',
    value: 32000,
    location: 'Los Angeles, CA',
    notesCount: 1,
    tags: ['Agency', 'Creative'],
  },
  {
    id: 'c-8',
    name: 'Brett Kincaid',
    avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80',
    email: 'brett@novusretail.com',
    phone: '+1 (303) 621-4439',
    title: 'Senior Merchandising Dir',
    company: 'Novus Retail Group',
    companyId: 'comp-8',
    status: 'Customer',
    owner: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80', email: 'alex@orbitcrm.com' },
    lastContacted: '3 weeks ago',
    value: 88000,
    location: 'Denver, CO',
    notesCount: 6,
    tags: ['Retail', 'Omnichannel'],
  },
  {
    id: 'c-9',
    name: 'Priya Sharma',
    avatar: 'https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=120&auto=format&fit=crop&q=80',
    email: 'psharma@stripeflow.ai',
    phone: '+1 (212) 433-8992',
    title: 'Lead Platform Architect',
    company: 'Stripeflow AI',
    companyId: 'comp-2',
    status: 'Active',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80', email: 'marcus@orbitcrm.com' },
    lastContacted: 'Yesterday',
    value: 34000,
    location: 'New York, NY',
    notesCount: 3,
    tags: ['Engineering', 'Technical'],
  },
  {
    id: 'c-10',
    name: 'Tobias Fray',
    avatar: 'https://images.unsplash.com/photo-1463453091185-61582044d556?w=120&auto=format&fit=crop&q=80',
    email: 'tobias@kinetics.tech',
    phone: '+1 (617) 502-3349',
    title: 'VP Manufacturing',
    company: 'Kinetics Robotics',
    companyId: 'comp-3',
    status: 'Lead',
    owner: { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80', email: 'sarah@orbitcrm.com' },
    lastContacted: 'Oct 8',
    value: 24000,
    location: 'Boston, MA',
    notesCount: 2,
    tags: ['Manufacturing'],
  },
  {
    id: 'c-11',
    name: 'Seraphina Holt',
    avatar: 'https://images.unsplash.com/photo-1548142813-c348350df52b?w=120&auto=format&fit=crop&q=80',
    email: 'sholt@loomissecur.com',
    phone: '+1 (512) 349-1125',
    title: 'Director of Procurement',
    company: 'Loomis Security',
    companyId: 'comp-4',
    status: 'Active',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80', email: 'marcus@orbitcrm.com' },
    lastContacted: '2 days ago',
    value: 100000,
    location: 'Austin, TX',
    notesCount: 7,
    tags: ['Procurement', 'Contracting'],
  },
  {
    id: 'c-12',
    name: 'Kofi Mensah',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80',
    email: 'k.mensah@chronoslog.com',
    phone: '+1 (312) 774-0985',
    title: 'VP Engineering Logistics',
    company: 'Chronos Logistics',
    companyId: 'comp-5',
    status: 'Active',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80', email: 'elena@orbitcrm.com' },
    lastContacted: '5 hours ago',
    value: 135000,
    location: 'Chicago, IL',
    notesCount: 5,
    tags: ['Tech Lead', 'Enterprise'],
  },
  {
    id: 'c-13',
    name: 'Nadia Rostam',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=120&auto=format&fit=crop&q=80',
    email: 'nadia@vercelify.io',
    phone: '+1 (415) 890-2109',
    title: 'Head of Developer Relations',
    company: 'Vercelify Dynamics',
    companyId: 'comp-1',
    status: 'Active',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80', email: 'elena@orbitcrm.com' },
    lastContacted: '4 days ago',
    value: 64000,
    location: 'San Francisco, CA',
    notesCount: 4,
    tags: ['DevRel', 'Community'],
  },
  {
    id: 'c-14',
    name: 'Elijah Becker',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80',
    email: 'e.becker@novusretail.com',
    phone: '+1 (303) 621-4444',
    title: 'E-Commerce VP',
    company: 'Novus Retail Group',
    companyId: 'comp-8',
    status: 'Lead',
    owner: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80', email: 'alex@orbitcrm.com' },
    lastContacted: '6 days ago',
    value: 45000,
    location: 'Denver, CO',
    notesCount: 2,
    tags: ['Growth', 'Retail'],
  },
  {
    id: 'c-15',
    name: 'Ingrid Solberg',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=120&auto=format&fit=crop&q=80',
    email: 'ingrid@synthetix.design',
    phone: '+1 (310) 902-8819',
    title: 'Managing Partner',
    company: 'Synthetix Media',
    companyId: 'comp-7',
    status: 'Churned',
    owner: { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80', email: 'sarah@orbitcrm.com' },
    lastContacted: 'Aug 14',
    value: 12000,
    location: 'Los Angeles, CA',
    notesCount: 6,
    tags: ['Past Account', 'Review in Q1'],
  },
  {
    id: 'c-16',
    name: 'Lucas Thorne',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?w=120&auto=format&fit=crop&q=80',
    email: 'lucas@hyperscalehealth.org',
    phone: '+1 (206) 881-2292',
    title: 'Director Data Systems',
    company: 'HyperScale Health',
    companyId: 'comp-6',
    status: 'Customer',
    owner: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80', email: 'alex@orbitcrm.com' },
    lastContacted: '3 days ago',
    value: 70000,
    location: 'Seattle, WA',
    notesCount: 3,
    tags: ['Analytics', 'Customer'],
  },
];

export const MOCK_DEALS: Deal[] = [
  {
    id: 'd-1',
    name: 'Vercelify Edge Deployment Suite',
    value: 84000,
    stage: 'Won',
    company: 'Vercelify Dynamics',
    companyId: 'comp-1',
    contactName: 'Alana Vance',
    contactEmail: 'alana@vercelify.io',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-09-02',
    probability: 100,
    priority: 'High',
    tags: ['Enterprise', 'Multi-year'],
  },
  {
    id: 'd-2',
    name: 'Chronos Real-time Tracking Addon',
    value: 175000,
    stage: 'Negotiation',
    company: 'Chronos Logistics',
    companyId: 'comp-5',
    contactName: 'Claire Dupont',
    contactEmail: 'cdupont@chronoslog.com',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-09-28',
    probability: 80,
    priority: 'High',
    tags: ['Custom SLA', 'Security Review'],
  },
  {
    id: 'd-3',
    name: 'Loomis SecOps Enterprise Gateway',
    value: 120000,
    stage: 'Won',
    company: 'Loomis Security',
    companyId: 'comp-4',
    contactName: 'Julian Sterling',
    contactEmail: 'jsterling@loomissecur.com',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-09-05',
    probability: 100,
    priority: 'High',
    tags: ['Annual Paid upfront'],
  },
  {
    id: 'd-4',
    name: 'Stripeflow AI Fraud Detection Module',
    value: 62000,
    stage: 'Proposal',
    company: 'Stripeflow AI',
    companyId: 'comp-2',
    contactName: 'Devon Mercer',
    contactEmail: 'devon@stripeflow.ai',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-10-15',
    probability: 60,
    priority: 'Medium',
    tags: ['Pilot SOW', 'Fintech'],
  },
  {
    id: 'd-5',
    name: 'Loomis Cloud Backup Redundancy',
    value: 100000,
    stage: 'Proposal',
    company: 'Loomis Security',
    companyId: 'comp-4',
    contactName: 'Seraphina Holt',
    contactEmail: 'sholt@loomissecur.com',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-10-20',
    probability: 55,
    priority: 'High',
    tags: ['Expansion', 'Procurement'],
  },
  {
    id: 'd-6',
    name: 'Novus Retail Omnichannel Sync',
    value: 88000,
    stage: 'Won',
    company: 'Novus Retail Group',
    companyId: 'comp-8',
    contactName: 'Brett Kincaid',
    contactEmail: 'brett@novusretail.com',
    owner: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-09-08',
    probability: 100,
    priority: 'Medium',
    tags: ['E-comm', 'POS Integration'],
  },
  {
    id: 'd-7',
    name: 'HyperScale HIPAA Cloud Storage',
    value: 54000,
    stage: 'Qualified',
    company: 'HyperScale Health',
    companyId: 'comp-6',
    contactName: 'Mateo Morales',
    contactEmail: 'mateo@hyperscalehealth.org',
    owner: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-11-01',
    probability: 40,
    priority: 'Medium',
    tags: ['Healthcare', 'Legal review'],
  },
  {
    id: 'd-8',
    name: 'Kinetics Autonomous Telemetry License',
    value: 48000,
    stage: 'Qualified',
    company: 'Kinetics Robotics',
    companyId: 'comp-3',
    contactName: 'Hanna Lindqvist',
    contactEmail: 'hanna@kinetics.tech',
    owner: { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-10-30',
    probability: 45,
    priority: 'Medium',
    tags: ['Hardware', 'IoT'],
  },
  {
    id: 'd-9',
    name: 'Synthetix Generative Workflow Suite',
    value: 32000,
    stage: 'Lead',
    company: 'Synthetix Media',
    companyId: 'comp-7',
    contactName: 'Zoe Nakamura',
    contactEmail: 'zoe@synthetix.design',
    owner: { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-11-15',
    probability: 20,
    priority: 'Low',
    tags: ['Creative', 'Inbound'],
  },
  {
    id: 'd-10',
    name: 'Novus Inventory Forecast Engine',
    value: 45000,
    stage: 'Lead',
    company: 'Novus Retail Group',
    companyId: 'comp-8',
    contactName: 'Elijah Becker',
    contactEmail: 'e.becker@novusretail.com',
    owner: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-11-20',
    probability: 25,
    priority: 'Low',
    tags: ['AI Forecast'],
  },
  {
    id: 'd-11',
    name: 'Stripeflow Custom Ledger Integration',
    value: 34000,
    stage: 'Negotiation',
    company: 'Stripeflow AI',
    companyId: 'comp-2',
    contactName: 'Priya Sharma',
    contactEmail: 'psharma@stripeflow.ai',
    owner: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-09-30',
    probability: 75,
    priority: 'Medium',
    tags: ['Engineering add-on'],
  },
  {
    id: 'd-12',
    name: 'Vercelify Multi-Tenant Audit Log',
    value: 64000,
    stage: 'Lost',
    company: 'Vercelify Dynamics',
    companyId: 'comp-1',
    contactName: 'Nadia Rostam',
    contactEmail: 'nadia@vercelify.io',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-08-15',
    probability: 0,
    priority: 'Medium',
    tags: ['Competitor feature gap', 'Lost to in-house'],
  },
  {
    id: 'd-13',
    name: 'Chronos Fleet Routing Engine',
    value: 135000,
    stage: 'Won',
    company: 'Chronos Logistics',
    companyId: 'comp-5',
    contactName: 'Kofi Mensah',
    contactEmail: 'k.mensah@chronoslog.com',
    owner: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80' },
    expectedCloseDate: '2026-09-10',
    probability: 100,
    priority: 'High',
    tags: ['Flagship Deal', 'Q3 Winner'],
  },
];

export const MOCK_ACTIVITIES: Activity[] = [
  {
    id: 'act-1',
    type: 'meeting',
    title: 'Executive alignment with Alana Vance & VP team',
    description: 'Reviewed the rollout timeline for Vercelify Edge Deployment Suite. Key milestone approved for Oct 1st launch.',
    timestamp: '15 minutes ago',
    author: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80' },
    relatedTo: { type: 'deal', id: 'd-1', name: 'Vercelify Edge Deployment Suite' },
  },
  {
    id: 'act-2',
    type: 'stage_change',
    title: 'Deal moved to Negotiation',
    description: 'Chronos Real-time Tracking Addon progressed from Proposal to Negotiation after CFO budget clearance.',
    timestamp: '2 hours ago',
    author: { name: 'Elena Rostova', avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80' },
    relatedTo: { type: 'deal', id: 'd-2', name: 'Chronos Real-time Tracking Addon' },
  },
  {
    id: 'act-3',
    type: 'call',
    title: 'Technical discovery call with Devon Mercer',
    description: 'Clarified custom webhook latency requirements (<40ms). Recommended dedicated cluster option for Stripeflow AI.',
    timestamp: '4 hours ago',
    author: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80' },
    relatedTo: { type: 'contact', id: 'c-2', name: 'Devon Mercer' },
  },
  {
    id: 'act-4',
    type: 'email',
    title: 'Sent revised Master Service Agreement (MSA)',
    description: 'Incorporated custom liability indemnification clause requested by Loomis legal department.',
    timestamp: 'Yesterday at 4:32 PM',
    author: { name: 'Marcus Chen', avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80' },
    relatedTo: { type: 'deal', id: 'd-3', name: 'Loomis SecOps Enterprise Gateway' },
  },
  {
    id: 'act-5',
    type: 'note',
    title: 'On-site quarterly check-in scheduled',
    description: 'Brett Kincaid confirmed executive dinner and roadmap preview session in Denver for late October.',
    timestamp: 'Yesterday at 11:15 AM',
    author: { name: 'Alex Rivera', avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80' },
    relatedTo: { type: 'contact', id: 'c-8', name: 'Brett Kincaid' },
  },
  {
    id: 'act-6',
    type: 'meeting',
    title: 'Robotics telemetry proof-of-concept kickoff',
    description: 'Connected with Hanna Lindqvist to initialize API staging tokens and demo data simulator.',
    timestamp: 'Sep 12, 2026',
    author: { name: 'Sarah Jenkins', avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=120&auto=format&fit=crop&q=80' },
    relatedTo: { type: 'deal', id: 'd-8', name: 'Kinetics Autonomous Telemetry License' },
  },
];

export const FUNNEL_STAGES = [
  { stage: 'Lead', count: 28, value: 310000, conversion: '100%' },
  { stage: 'Qualified', count: 18, value: 245000, conversion: '64%' },
  { stage: 'Proposal', count: 11, value: 212000, conversion: '39%' },
  { stage: 'Negotiation', count: 7, value: 209000, conversion: '25%' },
  { stage: 'Won', count: 5, value: 427000, conversion: '18%' },
];

export const REVENUE_MONTHS = [
  { month: 'Apr', revenue: 195, projected: 190 },
  { month: 'May', revenue: 235, projected: 220 },
  { month: 'Jun', revenue: 280, projected: 260 },
  { month: 'Jul', revenue: 310, projected: 300 },
  { month: 'Aug', revenue: 360, projected: 340 },
  { month: 'Sep', revenue: 427, projected: 410 },
];
